swagger: '2.0'
info:
  title: Vehicle Enquiry API
  version: 1.0.0
host: 54.191.244.98:8050
schemes:
  - http
produces:
  - application/json
paths:
  /vehicles:
    get:
      summary: Vehicle Enquiry
      description: |    
        Given a vehicle registration number and vehicle make, this returns tax and MOT information.
      parameters:
        - name: vrm
          in: query
          description: Vehicle registration number
          required: true
          type: string
        - name: make
          in: query
          description: Vehicle make
          required: true
          type: string
      responses:
        '200':
          description: Successful response
          schema:
            type: object
            properties:
              vehicleExists:
                type: boolean
                description: true if vehicle exists in database
              regMark:
                type: string
                description: the given vehicle registration number
              make:
                type: string
                description: the make of the vehicle
              validTax:
                type: boolean
                description: is the tax valid
              dateOfLiability:
                type: string
                description: date of liability
              validMot:
                type: boolean
                description: is mot valid
              motExpiryDt:
                type: string
                description: expiry date of mot
              firstRegDt:
                type: string
                description: date of first registration
              manufactureYr:
                type: string
                description: year the vehicle is manufactured
              cylinderCapacity:
                type: integer
                description: capacity of cylinder
              co2Emissions:
                type: integer
                description: co2 emissions from vehicle
              fuelType:
                type: string
                description: the type of fuel the vehicle produces
              status:
                type: string
                description: taxation status
              colour:
                type: string
                description: colour of vehicle
              typeApproval:
                type: string
                description: type approval
              wheelplan:
                type: string
                description: wheel plan
              revenueWeight:
                type: string
                description: revenue weight
        default:
          description: Unexpected error
          schema:
            type: object
            properties:
              code:
                type: integer
                format: int32
              message:
                type: string
              fields:
                type: string